export default function Home() {
  return (
    <div className="font-sans grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20">
      <h1 className="text-4xl font-bold text-center">AI Content Analyzer</h1>
      <div className="text-center text-lg max-w-2xl">
        <p className="mb-4">
          Welcome to the AI Content Analyzer! This tool helps you analyze and
          understand the content generated by AI models. Whether you're a
          developer, researcher, or enthusiast, this application provides
          insights into AI-generated text.
        </p>
      </div>
    </div>
  );
}
